version: "3.9"
services:
  reverseproxy:
    build:
      args:
        - Docker_Username="classicmeone" 
      context: ./udagram-proxy
    image: "classicmeone/reverseproxy"
  udagram-api-user:
    build:
      args:
        - Docker_Username="classicmeone"
      context: ./udagram-api-user
    image: "classicmeone/udagram-api-user"
  udagram-api-feed:
    build:
      args:
        - Docker_Username="classicmeone" 
      context: ./udagram-api-feed
    image: "classicmeone/udagram-api-feed"
  udagram-frontend:
    build:
      args:
        - Docker_Username="classicmeone" 
      context: ./udagram-frontend
    image: "classicmeone/udagram-frontend"



