language: nodejs

services:
  - docker

before_install:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker-compose up
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - bundle exec rake test
docker-compose -f docker-compose-build.yaml build --parallel
