name: Build and Deploy containers

on:
  push:
    branches:
      - dev
jobs:
  build-and-push:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: login to hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.Docker_Username}}
          password: ${{secrets.Docker_Password}}
      - name: build images
        run: docker compose -f docker-compose-build.yaml -e Docker_Username=${{secrets.Docker_Username}} build -d
      - name: push images
        run: docker compose -f docker-compose.yaml -e Docker_Username=${{secrets.Docker_Username}} push -d

